title: Tim D'Annecy
description: Tim's personal site
author: Tim D'Annecy
logo: /images/dannecyt.jpg
about: Graduate student in North Carolina

baseurl: "/"
url: "http://tdannecy.me"

disqus_shortname: tdannecy
google_analytics: UA-40317649-7

share:
  twitter_username: tdannecy
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
