title:              Tim D'Annecy
email:              tdannecy@gmail.com
description:        #
                    Tim D'Annecy's personal website.
baseurl:            /
url:                "http://tdannecy.me"
twitter_username:   tdannecy
github_username:    tdannecy

disqus: true
disqus_shortname: 'tdannecy'

markdown: kramdown