title: Tim D'Annecy
description: tdannecy@gmail.com
author: Tim D'Annecy
logo: /images/tdannecy.webp
about: tdannecy@gmail.com

baseurl: "http://tdannecy.me"
url: "http://tdannecy.me"

disqus_shortname: tdannecy
google_analytics: UA-40317649-7

share:

enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]

theme: jekyll-theme-cayman